/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QLCF.view;

import java.awt.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;


public class FrmAdminMain extends javax.swing.JFrame {
    private CardLayout cardLayout;
    
    public FrmAdminMain() {
        super("App Quản Lý Quán Cà phê Quân");
        setIconImage(new ImageIcon(getClass().getResource("/resources/image/logo cf 2.png")).getImage());
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/image/logo cf 2.png"));
        int width = logo.getWidth();
        int height = logo.getHeight();
        Image img = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        logo.setIcon(new ImageIcon(img));
        
        this.setLocationRelativeTo(null);
        cardLayout = new CardLayout();
        pnMain.setLayout(cardLayout);
        pnMain.add(new pnAdminHome(), "pnHome");
        cardLayout.show(pnMain, "pnHome");
        pnMain.add(new pnNhanVien(), "pnNV");
        pnMain.add(new pnMenu(), "pnMenu");
        pnMain.add(new pnNhaCungCap(), "pnNCC");
        pnMain.add(new pnDoanhThuTong(), "pnDTT");
        
        Timer timer = new Timer(1000, e -> {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss - dd/MM/yyyy");
        lbltime.setText(sdf.format(new Date()));
        });
        timer.start();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnSideBar = new javax.swing.JPanel();
        BtnTrangChu = new javax.swing.JButton();
        BtnQLMenu = new javax.swing.JButton();
        BtnQLNCC = new javax.swing.JButton();
        BtnQLDT = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        BtnQLNV = new javax.swing.JButton();
        lbltime = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();
        pnMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnSideBar.setBackground(new java.awt.Color(222, 184, 135));

        BtnTrangChu.setText("Trang chủ");
        BtnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTrangChuActionPerformed(evt);
            }
        });

        BtnQLMenu.setText("Quản lý Menu");
        BtnQLMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQLMenuActionPerformed(evt);
            }
        });

        BtnQLNCC.setText("Quản lý nhà cung cấp");
        BtnQLNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQLNCCActionPerformed(evt);
            }
        });

        BtnQLDT.setText("Quản lý doanh thu");
        BtnQLDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQLDTActionPerformed(evt);
            }
        });

        BtnQLNV.setText("Quản lý nhân viên");
        BtnQLNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQLNVActionPerformed(evt);
            }
        });

        lbltime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbltime.setText("Time");

        btnThoat.setText("Thoát");

        javax.swing.GroupLayout pnSideBarLayout = new javax.swing.GroupLayout(pnSideBar);
        pnSideBar.setLayout(pnSideBarLayout);
        pnSideBarLayout.setHorizontalGroup(
            pnSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnQLMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(BtnQLNCC, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(BtnQLDT, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(BtnQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnSideBarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltime, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnSideBarLayout.setVerticalGroup(
            pnSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSideBarLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(lbltime)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnQLMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnQLNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnQLDT, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1130, Short.MAX_VALUE)
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnQLMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQLMenuActionPerformed
        cardLayout.show(pnMain, "pnMenu");
    }//GEN-LAST:event_BtnQLMenuActionPerformed

    private void BtnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTrangChuActionPerformed
        cardLayout.show(pnMain, "pnHome");
    }//GEN-LAST:event_BtnTrangChuActionPerformed

    private void BtnQLNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQLNVActionPerformed
        cardLayout.show(pnMain, "pnNV");
    }//GEN-LAST:event_BtnQLNVActionPerformed

    private void BtnQLNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQLNCCActionPerformed
        cardLayout.show(pnMain, "pnNCC");
    }//GEN-LAST:event_BtnQLNCCActionPerformed

    private void BtnQLDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQLDTActionPerformed
        cardLayout.show(pnMain, "pnDTT");
    }//GEN-LAST:event_BtnQLDTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdminMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnQLDT;
    private javax.swing.JButton BtnQLMenu;
    private javax.swing.JButton BtnQLNCC;
    private javax.swing.JButton BtnQLNV;
    private javax.swing.JButton BtnTrangChu;
    private javax.swing.JButton btnThoat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lbltime;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnSideBar;
    // End of variables declaration//GEN-END:variables


}
