/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QLCF.view;

import java.awt.CardLayout;
import java.awt.Image;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Admin
 */
public class FrmNhanVienMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmNhanVienMain.class.getName());
    private final CardLayout cardLayout;
    /**
     * Creates new form FrmAdminNhanVien
     */
    public FrmNhanVienMain() {
        super("App Quản Lý Quán Cà Phê Quân");
        setIconImage(new ImageIcon(getClass().getResource("/resources/image/logo cf 2.png")).getImage());
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/resources/image/logo cf 2.png"));
        int width = logo.getWidth();
        int height = logo.getHeight();
        Image img = icon.getImage().getScaledInstance(width, height, Image.SCALE_SMOOTH);
        logo.setIcon(new ImageIcon(img));
        
        this.setLocationRelativeTo(null);
     
        cardLayout = new CardLayout();
        pnMain.setLayout(cardLayout);
        
        
        pnMain.add(new pnNhanVienHome(), "pnNhanVienHome");
        cardLayout.show(pnMain, "pnNhanVienHome");
        
        pnMain.add(new pnDoanhThuCa(), "pnDoanhThu");
        pnMain.add(new pnOrder(), "pnOrder");
        pnMain.add(new pnHangTonKho(), "pnHangTonKho");
        
        
        Timer timer = new Timer(1000, e -> {
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss - dd/MM/yyyy");
        lblTime.setText(sdf.format(new Date()));
        });
        timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnSideBar = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        BtnTrangChu = new javax.swing.JButton();
        pnDoanhThu = new javax.swing.JButton();
        BtnOrder = new javax.swing.JButton();
        BtnHangTonKho = new javax.swing.JButton();
        lblTime = new javax.swing.JLabel();
        BtnDangXuat = new javax.swing.JButton();
        pnMain = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnSideBar.setBackground(new java.awt.Color(222, 184, 135));

        BtnTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnTrangChu.setText("Trang chủ");
        BtnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTrangChuActionPerformed(evt);
            }
        });

        pnDoanhThu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pnDoanhThu.setText("Doanh thu ngày");
        pnDoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pnDoanhThuActionPerformed(evt);
            }
        });

        BtnOrder.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnOrder.setText("Order");
        BtnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOrderActionPerformed(evt);
            }
        });

        BtnHangTonKho.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnHangTonKho.setText("Kho");
        BtnHangTonKho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHangTonKhoActionPerformed(evt);
            }
        });

        lblTime.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTime.setText("Time");

        BtnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BtnDangXuat.setText("Thoát");
        BtnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDangXuatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnSideBarLayout = new javax.swing.GroupLayout(pnSideBar);
        pnSideBar.setLayout(pnSideBarLayout);
        pnSideBarLayout.setHorizontalGroup(
            pnSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtnHangTonKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnDoanhThu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtnTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnSideBarLayout.createSequentialGroup()
                .addGroup(pnSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnSideBarLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblTime))
                    .addGroup(pnSideBarLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addComponent(BtnDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnSideBarLayout.setVerticalGroup(
            pnSideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSideBarLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(BtnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnDoanhThu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnHangTonKho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(lblTime)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1123, Short.MAX_VALUE)
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnSideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnSideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTrangChuActionPerformed
        cardLayout.show(pnMain, "pnNhanVienHome");
    }//GEN-LAST:event_BtnTrangChuActionPerformed

    private void pnDoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pnDoanhThuActionPerformed
        cardLayout.show(pnMain, "pnDoanhThu");
    }//GEN-LAST:event_pnDoanhThuActionPerformed

    private void BtnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOrderActionPerformed
        cardLayout.show(pnMain, "pnOrder");
    }//GEN-LAST:event_BtnOrderActionPerformed

    private void BtnHangTonKhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHangTonKhoActionPerformed
        // TODO add your handling code here:
        cardLayout.show(pnMain, "pnHangTonKho");
    }//GEN-LAST:event_BtnHangTonKhoActionPerformed

    private void BtnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDangXuatActionPerformed
        this.dispose();
        FrmDangNhap LoginForm = new FrmDangNhap();
        LoginForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmNhanVienMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDangXuat;
    private javax.swing.JButton BtnHangTonKho;
    private javax.swing.JButton BtnOrder;
    private javax.swing.JButton BtnTrangChu;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel logo;
    private javax.swing.JButton pnDoanhThu;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnSideBar;
    // End of variables declaration//GEN-END:variables
}
