/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLCF.view;

import java.awt.BorderLayout;
import java.awt.Font;
import java.time.LocalTime;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author NoutSpace
 */
public class pnAdminHome extends javax.swing.JPanel {
    
    private JLabel lblGreeting;
    
    public pnAdminHome() {
    initComponents(); 
    setLayout(new BorderLayout());
    lblGreeting = new JLabel(getGreeting() + " !");
    lblGreeting.setFont(new Font("Constantia", Font.PLAIN, 36));
    lblGreeting.setHorizontalAlignment(SwingConstants.CENTER);
    add(lblGreeting, BorderLayout.CENTER);  
    }
    
    private String getGreeting(){
        int hour = LocalTime.now().getHour();
        if (hour >= 5 && hour < 12) {
            return "Chào buổi sáng";
        }else if (hour >= 12 && hour < 18) {
            return "Chào buổi chiều";
        }else{
            return "Chào buổi tối";
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(245, 235, 225));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1456, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 872, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}