/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLCF.view;

import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import QLCF.DAO.CaLamDAO;
import QLCF.DAO.DoanhThuDAO;
import QLCF.model.CaLam;
import QLCF.model.DoanhThu;

/**
 *
 * @author Admin
 */
public class pnDoanhThuCa extends javax.swing.JPanel {

    /**
     * Creates new form pnDoanhThuCa
     */
    public pnDoanhThuCa() {
        initComponents();
        dateChooser.setDate(new java.util.Date()); 
        dateChooser.setEnabled(false);             
        java.util.Date utilDate = dateChooser.getDate();
        if(utilDate == null){
            utilDate = new java.util.Date();
            dateChooser.setDate(utilDate);
        }
        
        java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
        
        loadtblDoanhThu(sqlDate);
        loadtblCaLam(sqlDate);
        TableColumnModel columnModelDoanhThu = tblDoanhThu.getColumnModel();
        columnModelDoanhThu.getColumn(0).setPreferredWidth(80);
        columnModelDoanhThu.getColumn(1).setPreferredWidth(80);
        columnModelDoanhThu.getColumn(2).setPreferredWidth(150);
        columnModelDoanhThu.getColumn(3).setPreferredWidth(100);
        columnModelDoanhThu.getColumn(4).setPreferredWidth(80);
        columnModelDoanhThu.getColumn(5).setPreferredWidth(80);
        tblDoanhThu.setRowHeight(25);

        
    }
    void loadtblDoanhThu(Date date){
       
        DefaultTableModel model = (DefaultTableModel) tblDoanhThu.getModel();
        model.setRowCount(0);
        
        DoanhThuDAO dao = new DoanhThuDAO();
        List<DoanhThu> list = dao.getDoanhThuByDate(date);
                
        double tongTienNgay = 0;
        Set<Integer> nhanVienSet = new HashSet<>();
        
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
        
        for(DoanhThu dt : list){

            model.addRow(new Object[]{
                dt.getId(),
                dt.getMaOrder(),
                sdf.format(dt.getThoi_gian()),
                dt.getTongTien(),
                dt.getMaNV(),
                dt.getMaCa()
            });
            tongTienNgay += dt.getTongTien();
            if(dt.getMaNV() > 0){
                nhanVienSet.add(dt.getMaNV());
            }
        }
        
        lblTongSoHoaDon.setText("Tổng số hoá đơn ngày: " + String.valueOf(list.size()));
        lblTongTienNgay.setText("Tổng tiền ngày: "+ String.format("%,.0f", tongTienNgay));
        lblSoNVCaLam.setText("Số nhân viên làm ngày: " + String.valueOf(nhanVienSet.size()));
    }
    void loadtblCaLam(Date date){
        DefaultTableModel model = (DefaultTableModel) tblCa.getModel();
        model.setRowCount(0);
        CaLamDAO dao = new CaLamDAO();
        List<CaLam> list = dao.getCaLamByDate(date);
        
        for(CaLam ca : list){
            model.addRow(new Object[]{
                ca.getMaCa(),
                ca.getMaNV(),
                ca.getTenNV(),
                ca.getTrang_thai()
            });
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        btnCheck = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoanhThu = new javax.swing.JTable();
        lblTongSoHoaDon = new javax.swing.JLabel();
        lblTongTienNgay = new javax.swing.JLabel();
        lblSoNVCaLam = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCa = new javax.swing.JTable();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jPanel1.setBackground(new java.awt.Color(222, 184, 135));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        btnCheck.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCheck.setText("Xem doanh thu");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(btnCheck)
                .addContainerGap(643, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chi tiết doanh thu ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblDoanhThu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã hoá đơn", "Mã Order", "Thời gian", "Tổng tiền", "Mã nhân viên", "Ca làm"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Float.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDoanhThu);

        jScrollPane2.setViewportView(jScrollPane1);

        lblTongSoHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTongSoHoaDon.setText("Tổng số hoá đơn ngày:");

        lblTongTienNgay.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTongTienNgay.setText("Tổng tiền ngày: ");

        lblSoNVCaLam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSoNVCaLam.setText("Số nhân viên làm ngày:");

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin của nhân viên", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblCa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã ca", "Mã nhân viên", "Tên nhân viên", "Trạng thái"
            }
        ));
        jScrollPane3.setViewportView(tblCa);

        jScrollPane4.setViewportView(jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTongSoHoaDon)
                    .addComponent(lblTongTienNgay)
                    .addComponent(lblSoNVCaLam))
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(lblTongSoHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(lblTongTienNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(lblSoNVCaLam, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
            java.util.Date today = new java.util.Date();
                java.sql.Date sqlDate = new java.sql.Date(today.getTime());

                loadtblDoanhThu(sqlDate);
                loadtblCaLam(sqlDate);
    }//GEN-LAST:event_btnCheckActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblSoNVCaLam;
    private javax.swing.JLabel lblTongSoHoaDon;
    private javax.swing.JLabel lblTongTienNgay;
    private javax.swing.JTable tblCa;
    private javax.swing.JTable tblDoanhThu;
    // End of variables declaration//GEN-END:variables
}
