/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLCF.view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import QLCF.DAO.NhaCungCapDAO;
import QLCF.model.MatHang;
import QLCF.model.NhaCungCap;

/**
 *
 * @author Admin
 */
public class pnHangTonKho extends javax.swing.JPanel {

    private String selectedMaNCC = null;

    /**
     * Creates new form pnNhaCungCap
     */
    public pnHangTonKho() {
        initComponents();
        loadTableDanhSach();
        tblDanhSach.getSelectionModel().addListSelectionListener(event ->{
            if(!event.getValueIsAdjusting()){
                int row = tblDanhSach.getSelectedRow();
                if(row != -1){
                    selectedMaNCC = tblDanhSach.getValueAt(row, 0).toString();
                }
            }
        });
                
        TableColumnModel columnModelDanhSach = tblDanhSach.getColumnModel();
        columnModelDanhSach.getColumn(0).setPreferredWidth(80);
        columnModelDanhSach.getColumn(1).setPreferredWidth(200);
        columnModelDanhSach.getColumn(2).setPreferredWidth(200);
        
        TableColumnModel columnModelTonKho = tblTonKho.getColumnModel();
        columnModelTonKho.getColumn(0).setPreferredWidth(80);
        columnModelTonKho.getColumn(1).setPreferredWidth(200);
        columnModelTonKho.getColumn(2).setPreferredWidth(80);
        columnModelTonKho.getColumn(3).setPreferredWidth(100);
        columnModelTonKho.getColumn(4).setPreferredWidth(80);
        
        tblDanhSach.setRowHeight(25);
        tblTonKho.setRowHeight(25);
    }
    
    private void loadTableDanhSach(){
        DefaultTableModel model = (DefaultTableModel) tblDanhSach.getModel();
        model.setRowCount(0);
        
        NhaCungCapDAO dao = new NhaCungCapDAO();
        List<NhaCungCap> list = dao.getAll();
        for(NhaCungCap ncc : list){
            model.addRow(new Object[]{
                ncc.getMaNCC(),
                ncc.getTenNCC(),
                ncc.getLoaiHang()
            });
        }
    }

    private void loadTableMatHangNCC(int maNCC){
        DefaultTableModel model = (DefaultTableModel) tblTonKho.getModel();
        model.setRowCount(0);
        
        NhaCungCapDAO dao = new NhaCungCapDAO();
        List<MatHang> list = dao.getMatHangByNCC(maNCC);
        for(MatHang mh : list){
            model.addRow(new Object[]{
                mh.getMaHang(),
                mh.getTenHang(),
                mh.getDonVi(),
                mh.getGiaNhap(),
                mh.getSoLuongTon()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnXemChiTiet = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtMaNCC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenNCC = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtLoaiHang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtLienHe = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTonKho = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTon = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();

        jLabel7.setText("jLabel7");

        jPanel1.setBackground(new java.awt.Color(222, 184, 135));

        btnXemChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXemChiTiet.setText("Xem chi tiết");
        btnXemChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemChiTietActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(btnXemChiTiet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnXemChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách nhà cung cấp", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã NCC", "Tên NCC", "Loại hàng"
            }
        ));
        jScrollPane1.setViewportView(tblDanhSach);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin chi tiết nhà cung cấp", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(8, 2));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Mã nhà cung cấp");
        jLabel3.setFocusTraversalPolicyProvider(true);
        jPanel2.add(jLabel3);

        txtMaNCC.setEditable(false);
        jPanel2.add(txtMaNCC);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tên nhà cung cấp");
        jLabel2.setFocusTraversalPolicyProvider(true);
        jPanel2.add(jLabel2);

        txtTenNCC.setEditable(false);
        jPanel2.add(txtTenNCC);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Loại hàng");
        jLabel4.setFocusTraversalPolicyProvider(true);
        jPanel2.add(jLabel4);

        txtLoaiHang.setEditable(false);
        jPanel2.add(txtLoaiHang);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Liên hệ");
        jLabel9.setFocusTraversalPolicyProvider(true);
        jPanel2.add(jLabel9);

        txtLienHe.setEditable(false);
        jPanel2.add(txtLienHe);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Số điện thoại");
        jLabel8.setFocusTraversalPolicyProvider(true);
        jPanel2.add(jLabel8);

        txtSDT.setEditable(false);
        jPanel2.add(txtSDT);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Email");
        jLabel5.setFocusTraversalPolicyProvider(true);
        jPanel2.add(jLabel5);

        txtEmail.setEditable(false);
        jPanel2.add(txtEmail);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Địa chỉ");
        jLabel6.setFocusTraversalPolicyProvider(true);
        jPanel2.add(jLabel6);

        txtDiaChi.setEditable(false);
        jPanel2.add(txtDiaChi);

        jScrollPane3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách hàng tồn kho", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18))); // NOI18N

        tblTonKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã hàng", "Tên hàng", "Đơn vị", "Giá nhập", "Số lượng tồn"
            }
        ));
        jScrollPane3.setViewportView(tblTonKho);

        jScrollPane5.setViewportView(jScrollPane3);

        btnSua.setBackground(new java.awt.Color(255, 102, 51));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Nhập số lượng tồn");

        btnUpdate.setBackground(new java.awt.Color(102, 255, 102));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 618, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 696, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtTon, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnXemChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemChiTietActionPerformed
        if(selectedMaNCC == null){
            JOptionPane.showMessageDialog(this, "Vui long chon mot nha cung cap");
            return;
        }
        
        int ma = Integer.parseInt(selectedMaNCC);
        
        NhaCungCapDAO dao = new NhaCungCapDAO();
        NhaCungCap ncc = dao.getNCCByID(ma);
        
        txtMaNCC.setText(String.valueOf(ncc.getMaNCC()));
        txtTenNCC.setText(ncc.getTenNCC());
        txtLoaiHang.setText(ncc.getLoaiHang());
        txtLienHe.setText(ncc.getLienHe());
        txtSDT.setText(ncc.getSoDienThoai());
        txtEmail.setText(ncc.getEmail());
        txtDiaChi.setText(ncc.getDiaChi());
        
        loadTableMatHangNCC(ma);
    }//GEN-LAST:event_btnXemChiTietActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed

        int rowMatHang = tblTonKho.getSelectedRow();
        if(rowMatHang == -1){
            JOptionPane.showMessageDialog(this, "Chọn một hàng từ bảng!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
            
        try{
            String soLuongMoi = txtTon.getText().trim();
            
            if(soLuongMoi.isEmpty()){
                JOptionPane.showMessageDialog(this, "Nhập số lượng tồn mới!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int tonMoi = Integer.parseInt(soLuongMoi);
            
            if(tonMoi < 0){
                JOptionPane.showMessageDialog(this, "Số lượng tồn không được âm!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            tblTonKho.setValueAt(tonMoi, rowMatHang, 4);
            
            txtTon.setText(String.valueOf(tonMoi));
                        
            JOptionPane.showMessageDialog(this, "Đã thay đổi số lượng tồn!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
        }catch(Exception e){
            e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        try{
            if(tblTonKho.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "Không có dữ liệu cập nhật!", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn lưu tất cả thay đổi xuống database?", "Xác nhận cập nhật", JOptionPane.YES_NO_OPTION);
            
            if(confirm == JOptionPane.YES_OPTION){
                NhaCungCapDAO dao = new NhaCungCapDAO();
                boolean hasChanges = false;
                boolean allsuccess = true;
                
                for(int row = 0; row < tblTonKho.getRowCount(); row++){
                    int maHang = Integer.parseInt(tblTonKho.getValueAt(row, 0).toString());
                    int soLuongTon = Integer.parseInt(tblTonKho.getValueAt(row, 4).toString());
                    
                    boolean success = dao.updateSoLuongTon(maHang, soLuongTon);
                    
                    if(success){
                        hasChanges = true;
                    }else{
                        allsuccess = false;
                        JOptionPane.showMessageDialog(this, "Cập nhật thất bại cho mã hàng: " + maHang, "Lỗi", JOptionPane.ERROR_MESSAGE);
                    }
                }
                if(hasChanges && allsuccess){
                    JOptionPane.showMessageDialog(this, "Cập nhật tất cả số lượng tồn kho thành công!", "Thành công", JOptionPane.INFORMATION_MESSAGE);
                }else if(hasChanges && !allsuccess){
                    JOptionPane.showMessageDialog(this, 
                        "Một số mặt hàng cập nhật thất bại!", 
                        "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(this, 
                        "Không có thay đổi nào được cập nhật!", 
                        "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        }catch(Exception e){
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnXemChiTiet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTable tblTonKho;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLienHe;
    private javax.swing.JTextField txtLoaiHang;
    private javax.swing.JTextField txtMaNCC;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenNCC;
    private javax.swing.JTextField txtTon;
    // End of variables declaration//GEN-END:variables
}
