/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLCF.view;

import java.awt.Color;
import java.awt.FlowLayout;
import java.io.File;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import QLCF.DAO.SanPhamDAO;
import QLCF.model.SanPham;


/**
 *
 * @author NoutSpace
 */
public class pnMenu extends javax.swing.JPanel {
    private JPanel currentRowPanel = null;
    private final int MAX_PER_ROW = 3;
    private JScrollPane scrollPane;
    //private JPanel item;
    
    public pnMenu() {
        initComponents();
        pnContainer.setLayout(new BoxLayout(pnContainer, BoxLayout.Y_AXIS));
        pnContainer.setBackground(new Color(240, 240, 240));
        loadMon();
    }
    
    private void loadMon() {
        SanPhamDAO spDao = new SanPhamDAO();
        List<SanPham> listSP = spDao.getAllSanPham();

        pnContainer.removeAll();
        currentRowPanel = null;

        for (SanPham sp : listSP) {
            // chua co hang | hang du 3 mon -> tao hang moi
            if (currentRowPanel == null || currentRowPanel.getComponentCount() >= MAX_PER_ROW) {
                currentRowPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 10, 10));
                currentRowPanel.setOpaque(false);
                pnContainer.add(currentRowPanel);
            }
            // tao Mon trong moi 
            pnItemMenu item = new pnItemMenu();
            item.setId(sp.getMaSP());
            item.setTen(sp.getTenSP());
            item.setGia(sp.getGia());
            if (sp.getHinhanh() != null) {
                item.setAnh(sp.getHinhanh());
            }
            currentRowPanel.add(item);
        }
        pnContainer.revalidate();
        pnContainer.repaint();
    }
    
    public static void main(String[] args) {
        pnMenu pn1 = new pnMenu();
        pn1.setVisible(true);
};
                
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnContainer = new javax.swing.JPanel();
        BtnThemMon = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(245, 235, 225));

        jScrollPane1.setBackground(new java.awt.Color(255, 0, 51));
        jScrollPane1.setViewportView(pnContainer);

        javax.swing.GroupLayout pnContainerLayout = new javax.swing.GroupLayout(pnContainer);
        pnContainer.setLayout(pnContainerLayout);
        pnContainerLayout.setHorizontalGroup(
            pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 582, Short.MAX_VALUE)
        );
        pnContainerLayout.setVerticalGroup(
            pnContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pnContainer);

        BtnThemMon.setText("Thêm món");
        BtnThemMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemMonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabel6.setText("Quản lý Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnThemMon, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(822, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnThemMon)
                .addContainerGap(168, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnThemMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemMonActionPerformed
        String tenSP = JOptionPane.showInputDialog(this, "Nhập tên món:");
        if (tenSP == null || tenSP.trim().isEmpty()) return;

        String giaStr = JOptionPane.showInputDialog(this, "Nhập giá món:");
        if (giaStr == null || giaStr.trim().isEmpty()) return;

        double gia = 0;
        try {
            gia = Double.parseDouble(giaStr);
        } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Giá không hợp lệ!");
        return;
        }
        
        String loaiSP = JOptionPane.showInputDialog(this, "Nhập loại sản phẩm :");
        if (loaiSP == null || loaiSP.trim().isEmpty()) return;

        // Chọn ảnh
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);
        byte[] dataHA = null;
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            try {
            dataHA = java.nio.file.Files.readAllBytes(file.toPath());
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }

        SanPhamDAO spDao = new SanPhamDAO();
        String newMaSP = spDao.generateNewMaSP(loaiSP); 
        SanPham sp = new SanPham(tenSP, gia, loaiSP, dataHA);
        sp.setMaSP(newMaSP);
        spDao.addSanPham(sp);

        // Hien thi len gdien
        if (currentRowPanel == null || currentRowPanel.getComponentCount() >= MAX_PER_ROW) {
            currentRowPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 10, 10));
            currentRowPanel.setOpaque(false);
            pnContainer.add(currentRowPanel);
        }

        pnItemMenu item = new pnItemMenu();
        item.setTen(sp.getTenSP());
        item.setGia(sp.getGia());
        if (sp.getHinhanh() != null) {
            item.setAnh(sp.getHinhanh());
        }
        JOptionPane.showMessageDialog(this, "Thêm món thành công !");

        currentRowPanel.add(item);
        pnContainer.revalidate();
        pnContainer.repaint();
     
    }//GEN-LAST:event_BtnThemMonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnThemMon;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnContainer;
    // End of variables declaration//GEN-END:variables
}
