/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLCF.view;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import QLCF.DAO.NhanVienDao;
import QLCF.DAO.TaiKhoanDao;
import QLCF.model.NhanVien;
import QLCF.model.TaiKhoan;
/**
 *
 * @author NoutSpace
 */
public class pnNhanVien extends javax.swing.JPanel {
    
    private DefaultTableModel model;
    private NhanVienDao nvdao;
    
    public pnNhanVien() {
        initComponents();
        nvdao = new NhanVienDao();
        
        Cbgioitinh.addItem("Select");
        Cbgioitinh.addItem("Nam");
        Cbgioitinh.addItem("Nu");
        
        tblNhanVien.setDefaultEditor(Object.class, null);
        loadTableData();
        
    }
    
    private void loadTableData() {
        List<NhanVien> list = nvdao.getAllNhanVien();
        model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);
        
        for (NhanVien nv : list) {
            model.addRow(new Object[]{ 
                nv.getId(),
                nv.getTen(),
                nv.getGioiTinh(),
                nv.getSdt(),
                nv.getNgaySinh(),
                nv.getTaikhoanId(),
                nv.getRole()
            });
        }
    }

    private void clearForm() {
        txtusername.setText("");
        txtfullname.setText("");
        txtphone.setText("");
        txtpassword.setText("");
        Cbgioitinh.setSelectedIndex(0);
        txtbirthday.setDate(null);
        txtfind.setText("");
    }
    
    private int getIdByUsername(String username) {
        int id = -1;
        String sql = "SELECT id FROM taikhoan WHERE username = ?";
        java.sql.Connection conn = null;
        java.sql.PreparedStatement pre = null;
        java.sql.ResultSet rs = null;
        
        try {
            conn = QLCF.connection.connectDB.getInstance();
            pre = conn.prepareStatement(sql);
            pre.setString(1, username);
            rs = pre.executeQuery();
            
            if (rs.next()) {
                id = rs.getInt("id");
                System.out.println("ID tài khoản tìm thấy: " + id);
            } else {
                System.out.println("Không tìm thấy username: " + username);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Lỗi getIdByUsername: " + e.getMessage());
        } finally {
            try {
                if (rs != null) rs.close();
                if (pre != null) pre.close();
                if (conn != null) QLCF.connection.connectDB.closeConnect(conn);
            } catch (Exception ignored) {}
        }
        return id;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfullname = new javax.swing.JTextField();
        txtbirthday = new com.toedter.calendar.JDateChooser();
        txtphone = new javax.swing.JTextField();
        BtnAdd = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        txtfind = new javax.swing.JTextField();
        BtnFind = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JPasswordField();
        Cbgioitinh = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(245, 235, 225));

        jLabel2.setText("Họ Tên :");

        jLabel3.setText("Giới tính :");

        jLabel4.setText("Ngày sinh :");

        jLabel5.setText("Số điện thoại :");

        txtbirthday.setDateFormatString("dd/MM/yyyy");

        BtnAdd.setText("Thêm");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        BtnDelete.setText("Xóa");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnUpdate.setText("Cập nhật");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Họ Tên", "Giới tính", "Số điện thoại", "Ngày sinh", "id tài khoản"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        BtnFind.setText("Tìm Kiếm");
        BtnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFindActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Constantia", 0, 18)); // NOI18N
        jLabel6.setText("Quản lý nhân viên");

        jLabel1.setText("Tên Tài Khoản :");

        jLabel7.setText("Mật Khẩu :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtusername))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(39, 39, 39))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtfullname, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                    .addComponent(Cbgioitinh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(153, 153, 153)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtbirthday, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(txtphone)
                            .addComponent(txtpassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtfind))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(433, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtfullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(jLabel4)
                    .addComponent(txtbirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cbgioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnFind))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        try {
            String role = "nhanvien";
            String username = txtusername.getText().trim();
            String password = new String(txtpassword.getPassword()).trim();
            String ten = txtfullname.getText().trim();
            String sdt = txtphone.getText().trim();
            String gioiTinh = Cbgioitinh.getSelectedItem().toString();
            java.util.Date utilDate = txtbirthday.getDate();

            if (username.isEmpty() || password.isEmpty() || ten.isEmpty() || sdt.isEmpty() || gioiTinh.equalsIgnoreCase("Select") || utilDate == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!","Cảnh báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            TaiKhoanDao tkDao = new TaiKhoanDao();
            NhanVienDao nvDao = new NhanVienDao();

            if (tkDao.checkRegister(username)) {
                JOptionPane.showMessageDialog(this, "Tài khoản này đã tồn tại!",
                        "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            TaiKhoan tkMoi = new TaiKhoan(username, password, role);
            tkDao.addTaiKhoan(tkMoi);

            int taiKhoanId = getIdByUsername(username);
            if (taiKhoanId <= 0) {
                JOptionPane.showMessageDialog(this, "Không thể lấy ID tài khoản!","Lỗi", JOptionPane.ERROR_MESSAGE);
                return;
            }

            java.sql.Date ngaySinh = new java.sql.Date(utilDate.getTime());
            NhanVien nv = new NhanVien();
            nv.setTen(ten);
            nv.setSdt(sdt);
            nv.setGioiTinh(gioiTinh);
            nv.setNgaySinh(ngaySinh);
            nv.setTaikhoanId(taiKhoanId);
            nv.setRole(role);

            
            nvDao.addNhanVien(nv);
            JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công!","Hệ thống", JOptionPane.INFORMATION_MESSAGE);

            loadTableData();
            clearForm();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm nhân viên: " + e.getMessage(),
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        int selectedRow = tblNhanVien.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần cập nhật!", 
                    "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int taikhoan_id = (int) tblNhanVien.getValueAt(selectedRow,5);
            int id = (int) tblNhanVien.getValueAt(selectedRow, 0);
            String ten = txtfullname.getText().trim();
            String gioiTinh = Cbgioitinh.getSelectedItem().toString();
            String sdt = txtphone.getText().trim();
            String username = txtusername.getText().trim();
            String password = new String(txtpassword.getPassword());
            java.util.Date utilDate = txtbirthday.getDate();

            if (ten.isEmpty() || sdt.isEmpty() || gioiTinh.equalsIgnoreCase("Select") || utilDate == null) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            java.sql.Date ngaySinh = new java.sql.Date(utilDate.getTime());
            NhanVien nv = new NhanVien();
            TaiKhoan tk = new TaiKhoan();
            
            tk.setId(taikhoan_id);
            tk.setUsername(username);
            tk.setPassword(password);
            tk.setRole("Nhan vien");

            nv.setId(id);
            nv.setTen(ten);
            nv.setGioiTinh(gioiTinh);
            nv.setSdt(sdt);
            nv.setNgaySinh(ngaySinh);
            
            NhanVienDao nvdao = new NhanVienDao();
            TaiKhoanDao tkdao = new TaiKhoanDao();
            nvdao.updateNhanVien(nv);
            tkdao.updateTaiKhoan(tk);
            
            JOptionPane.showMessageDialog(this, "Cập nhật nhân viên thành công!", "Hệ thống", JOptionPane.INFORMATION_MESSAGE);
            loadTableData();
            clearForm();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        int selectedRow = tblNhanVien.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên cần xóa!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, 
                "Bạn có chắc muốn xóa nhân viên này?", 
                "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) return;

        try {
            int id = (int) tblNhanVien.getValueAt(selectedRow, 0);
            NhanVienDao nvdao = new NhanVienDao();
            TaiKhoanDao tkdao = new TaiKhoanDao();
            tkdao.deleteTaiKhoan(id);
            nvdao.deleteNhanVien(id);
            
            JOptionPane.showMessageDialog(pnNhanVien.this, "Xóa nhân viên thành công!", "Hệ thống", JOptionPane.INFORMATION_MESSAGE);
            loadTableData();
            clearForm();
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi xóa: " + e.getMessage(), 
                    "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void BtnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFindActionPerformed
        String keyword = txtfind.getText().trim();
        
        if (keyword.isEmpty()) {
            loadTableData();
            return;
        }

        List<NhanVien> list = nvdao.findByName(keyword);
        model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);

        for (NhanVien nv : list) {
            model.addRow(new Object[]{
                nv.getId(),
                nv.getTen(),
                nv.getGioiTinh(),
                nv.getSdt(),
                nv.getNgaySinh(),
                nv.getTaikhoanId(),
                nv.getRole()
            });
        }

        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy nhân viên nào!", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BtnFindActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        int selectedRow = tblNhanVien.getSelectedRow();
        if (selectedRow != -1) {
            txtfullname.setText(tblNhanVien.getValueAt(selectedRow, 1).toString());
            Object gioiTinh = tblNhanVien.getValueAt(selectedRow, 2);
            if (gioiTinh != null) {
                String gt = gioiTinh.toString();
                if (gt.equalsIgnoreCase("Nam")) {
                    Cbgioitinh.setSelectedIndex(1);
                } else if (gt.equalsIgnoreCase("Nu")) {
                    Cbgioitinh.setSelectedIndex(2);
                } else {
                    Cbgioitinh.setSelectedIndex(0);
                }
            }
            
            Object sdt = tblNhanVien.getValueAt(selectedRow, 3);
            txtphone.setText(sdt != null ? sdt.toString() : "");
            
            Object ngaySinh = tblNhanVien.getValueAt(selectedRow, 4);
            if (ngaySinh != null && ngaySinh instanceof java.util.Date) {
                txtbirthday.setDate((java.util.Date) ngaySinh);
            } else {
                txtbirthday.setDate(null);
            }

            txtusername.setText("");
            txtpassword.setText("");
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnFind;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JComboBox<String> Cbgioitinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblNhanVien;
    private com.toedter.calendar.JDateChooser txtbirthday;
    private javax.swing.JTextField txtfind;
    private javax.swing.JTextField txtfullname;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables
}
